name: Check file size

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  check-large-files:
    runs-on: ubuntu-latest
    steps:
      - uses: ActionsDesk/lfs-warning@v3.0
        with:
          filesizelimit: 10485760
